### ISSUE TITLE
Review NPC multiattack output and tab index order

### ISSUE THREAD

**Issue by Actoba** [Actoba/roll20-character-sheets#65]
As per requests here - https://app.roll20.net/forum/post/1108598/#post-1255815

**Comment by Franbo** [comment]
Can you change the display order so that the multiattack output appears below the effect?  This way the first attack triggered is listed first in the chat output instead of last.

**Comment by Actoba** [comment]
Macro output will be significantly changing due across the sheet with the upcoming roll templates feature due to be released soon on Roll20.  As such i'm closing this issue and the changes for all sections of the sheet will be tracked through issue #79
