### ISSUE TITLE
I get a script error when using the attack button on Weapons.  DnD 5e character sheet

### ISSUE THREAD

**Issue by Greywalker1969** [Actoba/roll20-character-sheets#90]
I expect I'm missing something, as I don't see anyone else with this issue.  However, I have inserted my weapon information as:

  warhammer      STR        0       6        1d8         'check mark'     4      bludgeoning      -------    20

and when I try to use the attack macro button I recieve a syntax error:

SyntaxError: Expected "(", ".", "[", "abs(", "ceil(", "d", "floor(", "round(", "t", "{", [ |\t], [+|\-] or [0-9] but end of input found.

Is there something I'm missing, or something I should be doing before I click the attack button.  Granted, I am just in the initial processes of setting things up.  I have a clean map, I created the character, added a token and associated it, and tested it.  No additional tokens, no background, nothing yet.

Any help would be appreciated.

Thanks.
Dave

**Comment by mlenser** [comment]
Your crit damage field must be the same as your damage dice field.

**Comment by Actoba** [comment]
As mark mentioned, you need to have something filled in on the crit damage field.  Previously this was auto calculated (and not displayed) to match exactly what you had in the damage dice field but was split out to allow for features like extra damage on a crit and so on that is found in racial/class features or feats.

If you dont have anything that modifies your critical damage then the crit damage field should exactly match the damage dice section. 

Hope this helps
Actoba
