### ISSUE TITLE
Advantage Toggle instead / as alternative to Prompt

### ISSUE THREAD

**Issue by Solarswordsman** [Actoba/roll20-character-sheets#93]
For the 5th Edition Character Sheet:

As in the SRD/OGL version of the 5th edition character sheet, it would be expedient to allow for a simple toggle at the top of each page to switch between advantage/normal/disadvantage rolls. This would be an option in the dropdown from the top-right cog in addition to the current options (roll 2d20, roll 1d20, query for adv., etc.).

I'm looking at the format for these sheets and I might make the change myself and submit a PR, though as far as I know I have no way of testing it because I don't have a Pro account.

**Comment by mlenser** [comment]
Actoba has declared that no new development will occur on this sheet. I recommend swapping to the Shaped or OGL sheet if you want this functionality.

**Comment by Solarswordsman** [comment]
Ah my mistake.  I'll do that.  Thanks!
