### ISSUE TITLE
"Jack of All Trades" is not being applied

### ISSUE THREAD

**Issue by vinternet** [Actoba/roll20-character-sheets#96]
Using a Level 2 Bard with "Jack of All Trades" checked, dice rolls are not adding the +1 bonus.
Repro steps:

1. Open a character sheet for a Bard
2. Click the gear button to view the settings
3. Check "Jack of all Trades"
4. Click the Core button to go back to the character's skills
5. Click the name of a Skill the character is not proficient in, such as Nature.
6. The die is automatically rolled. Roll20 shows the result, and mousing over the result shows the calculation used. It's rolling 1d20+NAT, but not adding the +1 that Jack of all Trades should be adding. (Proficiency bonus is 2, JoaT should be adding half of that).
7. The same issue occurs with other skills, or when rolling straight off an ability modifier.
8. Tried: Opening and closing the character sheet, unchecking and rechecking the checkbox for JoaT, reloading Roll20.

Thank you for your help!

**Comment by Actoba** [comment]
This sounds very much like the "Shaped" 5e sheet and not the community one that this repo is for (and that is no longer in development for over a year now).  For example, skills on the Community 5e sheet are on a "Skills" tab on their own and it does not have a single Jack of all trades checkbox and instead requires you to set that on each skill via a dropdown menu option.

I cannot assist with the Shaped sheet i'm afraid and you will need to contact the author of that sheet for assistance.  I have verified that all is still working as intended with the community version of the sheet.

Good luck
Actoba

**Comment by vinternet** [comment]
Apologies, sounds like I was confused. Thanks for pointing me in the right
direction!
